/* Sentence Forge — built-in example lessons.
 *
 * Each example is authored with a small `sentence(text, specs)` helper:
 * every annotation targets a substring of the sentence (the nth occurrence),
 * so offsets are computed here and always land on token boundaries.
 * spec = [matchText, labelId, note?, nth?]   (nth defaults to 1)
 *
 * These load fully offline (no fetch) so the app still works from file://.
 * tools/smoke-test.js validates every annotation and re-emits samples/*.json.
 */
(function () {
  "use strict";
  var wjt = (window.wjt = window.wjt || {});

  function sentence(text, specs, types, notes) {
    var anns = [];
    specs.forEach(function (spec) {
      var match = spec[0], label = spec[1], note = spec[2], nth = spec[3] || 1;
      var at = -1;
      for (var n = 0; n < nth; n++) at = text.indexOf(match, at + 1);
      if (at === -1) {
        if (window.console) console.warn("example: no match for", JSON.stringify(match), "in", JSON.stringify(text));
        return;
      }
      anns.push({ id: wjt.uid(), start: at, end: at + match.length, label: label, note: note || "" });
    });
    var s = { text: text, annotations: anns };
    if (types) s.types = types;
    if (notes) s.notes = notes;
    return s;
  }

  /** Assemble a lesson and infer which teaching levels it uses. */
  function make(title, description, sentences) {
    var lesson = wjt.store.create(title);
    lesson.description = description;
    lesson.sentences = sentences;
    var used = {};
    sentences.forEach(function (s) {
      s.annotations.forEach(function (a) {
        var l = wjt.layerOf(a.label);
        if (l) used[l.id] = true;
      });
    });
    lesson.layers = wjt.LAYER_ORDER.filter(function (id) { return used[id]; });
    if (!lesson.layers.length) lesson.layers = ["pos"];
    return lesson;
  }

  /* ================================================================
   * Romeo and Juliet — the Prologue (the Chorus's sonnet)
   * Presented line by line so the verse structure stays visible.
   * ================================================================ */
  function buildRomeoJuliet() {
    return make(
      "Romeo and Juliet — Prologue",
      "Shakespeare's opening sonnet, spoken by the Chorus. Labeled line by line to show parts of speech, phrases, and the relative and adverbial clauses woven through the verse. Because the sonnet's sentences run across several lines, only the two lines that stand alone as complete sentences carry a sentence-type badge — the rest are fragments.",
      [
        sentence("Two households, both alike in dignity,", [
          ["Two", "determiner", "A number acting as a determiner."],
          ["households,", "noun"],
          ["both", "pronoun", "Stands for the two households."],
          ["alike", "adjective"],
          ["in dignity,", "prepositional-phrase"],
          ["in", "preposition"],
          ["dignity,", "noun"],
        ]),
        sentence("In fair Verona, where we lay our scene,", [
          ["In fair Verona,", "prepositional-phrase"],
          ["In", "preposition"],
          ["fair", "adjective"],
          ["Verona,", "noun"],
          ["where we lay our scene,", "relative-clause", "Describes Verona — it tells which place."],
          ["where", "adverb", "A relative adverb — it introduces the clause."],
          ["we", "pronoun"],
          ["lay", "verb"],
          ["our", "determiner"],
          ["scene,", "noun"],
        ]),
        sentence("From ancient grudge break to new mutiny,", [
          ["From ancient grudge", "prepositional-phrase"],
          ["From", "preposition"],
          ["ancient", "adjective"],
          ["grudge", "noun"],
          ["break", "verb"],
          ["to new mutiny,", "prepositional-phrase"],
          ["to", "preposition"],
          ["new", "adjective"],
          ["mutiny,", "noun"],
        ]),
        sentence("Where civil blood makes civil hands unclean.", [
          ["Where civil blood makes civil hands unclean.", "adverbial-clause", "Tells the result of the grudge breaking out."],
          ["Where", "adverb", "A relative adverb — it opens the clause."],
          ["civil", "adjective"],
          ["blood", "noun"],
          ["makes", "verb"],
          ["civil", "adjective", "", 2],
          ["hands", "noun"],
          ["unclean.", "adjective", "An object complement — it describes 'hands'."],
        ]),
        sentence("From forth the fatal loins of these two foes", [
          ["From", "preposition"],
          ["forth", "adverb"],
          ["the", "determiner"],
          ["fatal", "adjective"],
          ["loins", "noun"],
          ["of these two foes", "prepositional-phrase"],
          ["of", "preposition"],
          ["these", "determiner"],
          ["two", "determiner"],
          ["foes", "noun"],
        ]),
        sentence("A pair of star-cross'd lovers take their life;", [
          ["A pair of star-cross'd lovers", "noun-phrase", "The full subject of this clause."],
          ["A", "determiner"],
          ["pair", "noun"],
          ["of star-cross'd lovers", "prepositional-phrase"],
          ["of", "preposition"],
          ["star-cross'd", "adjective"],
          ["lovers", "noun"],
          ["take", "verb"],
          ["their life;", "direct-object"],
          ["their", "determiner"],
          ["life;", "noun"],
          ["A pair of star-cross'd lovers", "complete-subject"],
          ["pair", "simple-subject"],
          ["take their life;", "complete-predicate"],
          ["take", "simple-predicate"],
          ["A pair of star-cross'd lovers take their life;", "independent-clause"],
        ], { structure: "simple", purpose: "declarative" }),
        sentence("Whose misadventured piteous overthrows", [
          ["Whose", "determiner", "A relative possessive — it points back to the lovers."],
          ["misadventured", "adjective"],
          ["piteous", "adjective"],
          ["overthrows", "noun"],
        ]),
        sentence("Do with their death bury their parents' strife.", [
          ["Do", "verb", "A helping (auxiliary) verb paired with 'bury'."],
          ["with their death", "prepositional-phrase"],
          ["with", "preposition"],
          ["their", "determiner"],
          ["death", "noun"],
          ["bury", "verb"],
          ["their", "determiner", "", 2],
          ["parents'", "noun"],
          ["strife.", "noun"],
        ]),
        sentence("The fearful passage of their death-mark'd love,", [
          ["The fearful passage of their death-mark'd love,", "noun-phrase", "Part of the long subject of 'Is' two lines down."],
          ["The", "determiner"],
          ["fearful", "adjective"],
          ["passage", "noun"],
          ["of their death-mark'd love,", "prepositional-phrase"],
          ["of", "preposition"],
          ["their", "determiner"],
          ["death-mark'd", "adjective"],
          ["love,", "noun"],
        ]),
        sentence("And the continuance of their parents' rage,", [
          ["And", "conjunction"],
          ["the", "determiner"],
          ["continuance", "noun"],
          ["of their parents' rage,", "prepositional-phrase"],
          ["of", "preposition"],
          ["their", "determiner"],
          ["parents'", "noun"],
          ["rage,", "noun"],
        ]),
        sentence("Which, but their children's end, nought could remove,", [
          ["Which,", "pronoun", "A relative pronoun standing for the parents' rage."],
          ["but their children's end,", "prepositional-phrase", "Here 'but' means 'except for'."],
          ["but", "preposition", "Here 'but' means 'except for'."],
          ["their", "determiner"],
          ["children's", "noun"],
          ["end,", "noun"],
          ["nought", "pronoun", "An old word for 'nothing'."],
          ["could", "verb"],
          ["remove,", "verb"],
        ]),
        sentence("Is now the two hours' traffic of our stage;", [
          ["Is", "verb"],
          ["now", "adverb"],
          ["the", "determiner"],
          ["two", "determiner"],
          ["hours'", "noun"],
          ["traffic", "noun"],
          ["of our stage;", "prepositional-phrase"],
          ["of", "preposition"],
          ["our", "determiner", "", 2],
          ["stage;", "noun"],
        ]),
        sentence("The which if you with patient ears attend,", [
          ["The", "determiner"],
          ["which", "pronoun", "A relative pronoun."],
          ["if you with patient ears attend,", "adverbial-clause", "A condition — 'if' you listen patiently."],
          ["if", "conjunction"],
          ["you", "pronoun"],
          ["with patient ears", "prepositional-phrase"],
          ["with", "preposition"],
          ["patient", "adjective"],
          ["ears", "noun"],
          ["attend,", "verb"],
        ]),
        sentence("What here shall miss, our toil shall strive to mend.", [
          ["What here shall miss,", "noun-clause", "Acts as the object of 'mend' — whatever the play leaves out."],
          ["What", "pronoun"],
          ["here", "adverb"],
          ["shall", "verb"],
          ["miss,", "verb"],
          ["our", "determiner"],
          ["toil", "noun"],
          ["shall", "verb", "", 2],
          ["strive", "verb"],
          ["to mend.", "infinitive-phrase"],
          ["to mend.", "infinitive", "The infinitive — “to” plus the base verb."],
          ["What", "simple-subject", "The pronoun “what” is the subject of its noun clause."],
          ["here shall miss,", "complete-predicate"],
          ["shall miss,", "simple-predicate"],
          ["our toil", "complete-subject"],
          ["toil", "simple-subject"],
          ["shall strive to mend.", "complete-predicate"],
          ["shall strive", "simple-predicate"],
          ["our toil shall strive to mend.", "independent-clause"],
        ], { structure: "complex", purpose: "declarative" }),
      ]
    );
  }

  /* ================================================================
   * The Great Gatsby — closing paragraph (F. Scott Fitzgerald)
   * Em-dash breaks lightly regularized into full stops for clarity.
   * ================================================================ */
  function buildGatsby() {
    return make(
      "The Great Gatsby — Closing Lines",
      "Fitzgerald's famous final paragraph. A showcase of appositive, prepositional, and participial phrases plus a relative clause and a compound sentence. (Em-dashes lightly regularized into sentences.)",
      [
        sentence("Gatsby believed in the green light, the orgastic future that year by year recedes before us.", [
          ["Gatsby", "noun", "A proper noun and the subject of the sentence."],
          ["Gatsby", "simple-subject"],
          ["believed", "verb"],
          ["in the green light,", "prepositional-phrase"],
          ["in", "preposition"],
          ["the", "determiner"],
          ["green", "adjective"],
          ["light,", "noun"],
          ["the orgastic future", "appositive-phrase", "Renames 'the green light'."],
          ["the", "determiner", "", 2],
          ["orgastic", "adjective"],
          ["future", "noun"],
          ["that year by year recedes before us.", "relative-clause", "Describes 'the future'."],
          ["that", "pronoun"],
          ["year", "noun"],
          ["by", "preposition", "", 2],
          ["year", "noun", "", 2],
          ["recedes", "verb"],
          ["before us.", "prepositional-phrase"],
          ["before", "preposition"],
          ["us.", "pronoun"],
          ["believed in the green light, the orgastic future that year by year recedes before us.", "complete-predicate"],
          ["believed", "simple-predicate"],
          ["that", "simple-subject", "The relative pronoun is the subject of its own clause."],
          ["recedes before us.", "complete-predicate"],
          ["recedes", "simple-predicate"],
          ["Gatsby believed in the green light, the orgastic future that year by year recedes before us.", "independent-clause"],
        ], { structure: "complex", purpose: "declarative" }),
        sentence("It eluded us then, but that's no matter.", [
          ["It", "pronoun"],
          ["eluded", "verb"],
          ["us", "pronoun"],
          ["then,", "adverb"],
          ["but", "conjunction", "Joins two independent clauses into a compound sentence."],
          ["that's", "pronoun"],
          ["no", "determiner"],
          ["matter.", "noun"],
          ["It", "simple-subject"],
          ["eluded us then,", "complete-predicate"],
          ["eluded", "simple-predicate"],
          ["us", "direct-object"],
          ["that's", "simple-subject", "The contraction “that’s” = “that is” — “that” is the subject and “’s” is the linking verb."],
          ["that's no matter.", "complete-predicate"],
          ["no matter.", "predicate-nominative", "Renames “that” after the linking verb “is.”"],
          ["It eluded us then,", "independent-clause"],
          ["but that's no matter.", "independent-clause"],
        ], { structure: "compound", purpose: "declarative" }),
        sentence("Tomorrow we will run faster, and stretch out our arms farther.", [
          ["Tomorrow", "adverb"],
          ["we", "pronoun"],
          ["will", "verb", "A helping verb forming the future tense."],
          ["run", "verb"],
          ["faster,", "adverb"],
          ["and", "conjunction"],
          ["stretch", "verb"],
          ["out", "adverb", "A particle completing the phrasal verb 'stretch out'."],
          ["our arms", "direct-object"],
          ["our", "determiner"],
          ["arms", "noun"],
          ["farther.", "adverb"],
          ["we", "simple-subject"],
          ["will run faster, and stretch out our arms farther.", "compound-predicate", "One subject, two verbs joined by “and.”"],
          ["will run", "simple-predicate"],
          ["stretch", "simple-predicate"],
          ["Tomorrow we will run faster, and stretch out our arms farther.", "independent-clause"],
        ], { structure: "simple", purpose: "declarative" }),
        sentence("So we beat on, boats against the current, borne back ceaselessly into the past.", [
          ["So", "conjunction"],
          ["we", "pronoun"],
          ["beat", "verb"],
          ["on,", "adverb"],
          ["boats against the current,", "appositive-phrase", "A metaphor renaming 'we'."],
          ["boats", "noun"],
          ["against the current,", "prepositional-phrase"],
          ["against", "preposition"],
          ["the", "determiner"],
          ["current,", "noun"],
          ["borne back ceaselessly into the past.", "participial-phrase", "'Borne' is a past participle describing the boats."],
          ["borne", "verb"],
          ["back", "adverb"],
          ["ceaselessly", "adverb"],
          ["into the past.", "prepositional-phrase"],
          ["into", "preposition"],
          ["the", "determiner", "", 2],
          ["past.", "noun"],
          ["we", "simple-subject"],
          ["beat on, boats against the current, borne back ceaselessly into the past.", "complete-predicate"],
          ["beat", "simple-predicate"],
          ["So we beat on, boats against the current, borne back ceaselessly into the past.", "independent-clause"],
        ], { structure: "simple", purpose: "declarative" }),
      ]
    );
  }

  /* ================================================================
   * Frankenstein — the creation scene (Mary Shelley)
   * ================================================================ */
  function buildFrankenstein() {
    return make(
      "Frankenstein — The Creation",
      "Victor brings the creature to life. Rich in complex sentences: a cleft construction, relative clauses, noun phrases, and a semicolon-joined compound sentence.",
      [
        sentence("It was on a dreary night of November that I beheld the accomplishment of my toils.", [
          ["It", "pronoun"],
          ["was", "verb"],
          ["on a dreary night", "prepositional-phrase"],
          ["on", "preposition"],
          ["a", "determiner", "", 2],
          ["dreary", "adjective"],
          ["night", "noun"],
          ["of November", "prepositional-phrase"],
          ["of", "preposition"],
          ["November", "noun"],
          ["that I beheld the accomplishment of my toils.", "dependent-clause", "A cleft sentence: 'It was... that I beheld...' emphasizes the night."],
          ["that", "conjunction", "Introduces the cleft clause."],
          ["I", "pronoun", "", 2],
          ["beheld", "verb"],
          ["the accomplishment of my toils.", "noun-phrase", "The direct object — what Victor beheld."],
          ["the", "determiner"],
          ["accomplishment", "noun"],
          ["of my toils.", "prepositional-phrase"],
          ["of", "preposition", "", 2],
          ["my", "determiner"],
          ["toils.", "noun"],
          ["It", "simple-subject"],
          ["was on a dreary night of November", "complete-predicate"],
          ["was", "simple-predicate"],
          ["It was on a dreary night of November", "independent-clause"],
          ["I", "simple-subject", "", 2],
          ["beheld the accomplishment of my toils.", "complete-predicate"],
          ["beheld", "simple-predicate"],
          ["the accomplishment of my toils.", "direct-object", "What Victor beheld."],
        ], { structure: "complex", purpose: "declarative" },
        "A cleft sentence: “It was … that I beheld …” front-loads the dreary November night for emphasis. The plain form is “I beheld the accomplishment of my toils on a dreary night of November.”"),
        sentence("With an anxiety that almost amounted to agony, I collected the instruments of life around me.", [
          ["With an anxiety", "prepositional-phrase"],
          ["With", "preposition"],
          ["an", "determiner"],
          ["anxiety", "noun"],
          ["that almost amounted to agony,", "relative-clause", "Describes 'anxiety'."],
          ["that", "pronoun"],
          ["almost", "adverb"],
          ["amounted", "verb"],
          ["to agony,", "prepositional-phrase"],
          ["to", "preposition"],
          ["agony,", "noun"],
          ["I", "pronoun"],
          ["collected", "verb"],
          ["the instruments of life", "noun-phrase"],
          ["the", "determiner"],
          ["instruments", "noun"],
          ["of life", "prepositional-phrase"],
          ["of", "preposition"],
          ["life", "noun"],
          ["around me.", "prepositional-phrase"],
          ["around", "preposition"],
          ["me.", "pronoun"],
          ["that", "simple-subject", "The relative pronoun is the subject of its clause."],
          ["almost amounted to agony,", "complete-predicate"],
          ["amounted", "simple-predicate"],
          ["I", "simple-subject"],
          ["collected the instruments of life around me.", "complete-predicate"],
          ["collected", "simple-predicate"],
          ["the instruments of life", "direct-object"],
          ["With an anxiety that almost amounted to agony, I collected the instruments of life around me.", "independent-clause"],
        ], { structure: "complex", purpose: "declarative" }),
        sentence("I saw the dull yellow eye of the creature open; it breathed hard, and a convulsive motion agitated its limbs.", [
          ["I", "pronoun"],
          ["saw", "verb"],
          ["the dull yellow eye of the creature", "noun-phrase", "The direct object of 'saw'."],
          ["the", "determiner"],
          ["dull", "adjective"],
          ["yellow", "adjective"],
          ["eye", "noun"],
          ["of the creature", "prepositional-phrase"],
          ["of", "preposition"],
          ["the", "determiner", "", 2],
          ["creature", "noun"],
          ["open;", "verb", "A bare infinitive completing 'saw the eye open'."],
          ["it", "pronoun"],
          ["breathed", "verb"],
          ["hard,", "adverb"],
          ["and", "conjunction"],
          ["a convulsive motion", "noun-phrase"],
          ["a", "determiner", "", 6],
          ["convulsive", "adjective"],
          ["motion", "noun"],
          ["agitated", "verb"],
          ["its", "determiner"],
          ["limbs.", "noun"],
          ["I", "simple-subject"],
          ["saw the dull yellow eye of the creature open;", "complete-predicate"],
          ["saw", "simple-predicate"],
          ["the dull yellow eye of the creature", "direct-object"],
          ["I saw the dull yellow eye of the creature open;", "independent-clause"],
          ["it", "simple-subject"],
          ["breathed hard,", "complete-predicate"],
          ["breathed", "simple-predicate"],
          ["it breathed hard,", "independent-clause"],
          ["a convulsive motion", "complete-subject"],
          ["motion", "simple-subject"],
          ["agitated its limbs.", "complete-predicate"],
          ["agitated", "simple-predicate"],
          ["its limbs.", "direct-object"],
          ["and a convulsive motion agitated its limbs.", "independent-clause"],
        ], { structure: "compound", purpose: "declarative" }),
      ]
    );
  }

  /* ================================================================
   * Dracula — Harker's first sight of the Count (Bram Stoker)
   * ================================================================ */
  function buildDracula() {
    return make(
      "Dracula — The Count Appears",
      "Jonathan Harker meets Count Dracula. Features an inverted subject, participial phrases, and both relative and adverbial clauses.",
      [
        sentence("Within stood a tall old man, clean-shaven save for a long white moustache, and clad in black from head to foot.", [
          ["Within", "adverb"],
          ["stood", "verb"],
          ["a tall old man,", "noun-phrase", "The subject — inverted so it follows the verb."],
          ["a", "determiner"],
          ["tall", "adjective"],
          ["old", "adjective"],
          ["man,", "noun"],
          ["clean-shaven", "adjective"],
          ["save for a long white moustache,", "prepositional-phrase", "'Save for' means 'except for'."],
          ["save", "preposition", "'Save for' means 'except for'."],
          ["for", "preposition"],
          ["a", "determiner", "", 7],
          ["long", "adjective"],
          ["white", "adjective"],
          ["moustache,", "noun"],
          ["and", "conjunction"],
          ["clad in black from head to foot.", "participial-phrase", "'Clad' is a past participle describing the man."],
          ["clad", "verb"],
          ["in black", "prepositional-phrase"],
          ["in", "preposition", "", 2],
          ["black", "noun"],
          ["from head to foot.", "prepositional-phrase"],
          ["from", "preposition"],
          ["head", "noun"],
          ["to", "preposition", "", 2],
          ["foot.", "noun"],
          ["a tall old man,", "complete-subject"],
          ["man,", "simple-subject"],
          ["Within stood", "complete-predicate"],
          ["stood", "simple-predicate"],
          ["Within stood a tall old man, clean-shaven save for a long white moustache, and clad in black from head to foot.", "independent-clause"],
        ], { structure: "simple", purpose: "declarative" }),
        sentence("He held in his hand an antique silver lamp, which threw long, quivering shadows as it flickered in the draught of the open door.", [
          ["He", "pronoun"],
          ["He", "simple-subject"],
          ["held", "verb"],
          ["in his hand", "prepositional-phrase"],
          ["in", "preposition"],
          ["his", "determiner"],
          ["hand", "noun"],
          ["an antique silver lamp,", "noun-phrase", "The direct object of 'held'."],
          ["an", "determiner", "", 2],
          ["antique", "adjective"],
          ["silver", "adjective"],
          ["lamp,", "noun"],
          ["which threw long, quivering shadows", "relative-clause", "Describes 'the lamp'."],
          ["which", "pronoun"],
          ["threw", "verb"],
          ["long,", "adjective"],
          ["quivering", "adjective", "A present participle used as an adjective."],
          ["shadows", "noun"],
          ["as it flickered in the draught of the open door.", "adverbial-clause", "Tells when the shadows were thrown."],
          ["as", "conjunction"],
          ["it", "pronoun"],
          ["flickered", "verb"],
          ["in the draught", "prepositional-phrase"],
          ["in", "preposition", "", 3],
          ["the", "determiner"],
          ["draught", "noun"],
          ["of the open door.", "prepositional-phrase"],
          ["of", "preposition"],
          ["the", "determiner", "", 2],
          ["open", "adjective"],
          ["door.", "noun"],
          ["held in his hand an antique silver lamp,", "complete-predicate"],
          ["held", "simple-predicate"],
          ["an antique silver lamp,", "direct-object"],
          ["which", "simple-subject", "The relative pronoun is the subject of its clause."],
          ["threw long, quivering shadows", "complete-predicate"],
          ["threw", "simple-predicate"],
          ["long, quivering shadows", "direct-object"],
          ["it", "simple-subject"],
          ["flickered in the draught of the open door.", "complete-predicate"],
          ["flickered", "simple-predicate"],
          ["He held in his hand an antique silver lamp, which threw long, quivering shadows as it flickered in the draught of the open door.", "independent-clause"],
        ], { structure: "complex", purpose: "declarative" }),
      ]
    );
  }

  /* ================================================================
   * Kinds of Sentences — a purpose-built showcase of sentence types.
   * Four purposes (declarative, interrogative, imperative, exclamatory)
   * and four structures (simple, compound, complex, compound-complex),
   * each sentence tagged so students can practice quick identification.
   * ================================================================ */
  function buildKinds() {
    return make(
      "Kinds of Sentences",
      "A plain-language set for teaching sentence types at a glance: the four purposes and the four structures, each sentence tagged. Great for the “name that sentence” quiz.",
      [
        sentence("The team practiced hard all week.", [
          ["The", "determiner"],
          ["team", "noun"],
          ["practiced", "verb"],
          ["hard", "adverb"],
          ["all", "determiner"],
          ["week.", "noun"],
          ["The team", "complete-subject"],
          ["team", "simple-subject"],
          ["practiced hard all week.", "complete-predicate"],
          ["practiced", "simple-predicate"],
          ["The team practiced hard all week.", "independent-clause"],
        ], { structure: "simple", purpose: "declarative" }),
        sentence("Are you ready for the big game?", [
          ["Are", "verb", "The verb comes first because it is a question."],
          ["you", "pronoun"],
          ["you", "simple-subject"],
          ["Are", "simple-predicate", "The verb — in a question it moves ahead of the subject."],
          ["ready", "adjective", "A predicate adjective describing “you.”"],
          ["ready", "complement"],
          ["for the big game?", "prepositional-phrase"],
          ["for", "preposition"],
          ["the", "determiner"],
          ["big", "adjective"],
          ["game?", "noun"],
          ["Are you ready for the big game?", "independent-clause"],
        ], { structure: "simple", purpose: "interrogative" }),
        sentence("Pass the ball to me.", [
          ["Pass", "verb", "A command — the subject “you” is understood."],
          ["Pass", "understood-subject", "The unstated “(you)” that the command is aimed at."],
          ["Pass the ball to me.", "complete-predicate", "The whole sentence is the predicate; the subject is the understood “you.”"],
          ["Pass", "simple-predicate"],
          ["the", "determiner"],
          ["ball", "noun"],
          ["the ball", "direct-object"],
          ["to", "preposition"],
          ["to me.", "prepositional-phrase"],
          ["me.", "pronoun"],
          ["Pass the ball to me.", "independent-clause"],
        ], { structure: "simple", purpose: "imperative" }),
        sentence("We finally won the championship!", [
          ["We", "pronoun"],
          ["We", "simple-subject"],
          ["finally", "adverb"],
          ["won", "verb"],
          ["finally won the championship!", "complete-predicate"],
          ["won", "simple-predicate"],
          ["the", "determiner"],
          ["championship!", "noun"],
          ["the championship!", "direct-object"],
          ["We finally won the championship!", "independent-clause"],
        ], { structure: "simple", purpose: "exclamatory" }),
        sentence("The rain stopped, and the sun came out.", [
          ["The", "determiner"],
          ["rain", "noun"],
          ["stopped,", "verb"],
          ["and", "conjunction", "A coordinating conjunction joining two independent clauses."],
          ["the", "determiner"],
          ["sun", "noun"],
          ["came", "verb"],
          ["out.", "adverb"],
          ["The rain", "complete-subject"],
          ["rain", "simple-subject"],
          ["stopped,", "simple-predicate"],
          ["the sun", "complete-subject"],
          ["sun", "simple-subject"],
          ["came out.", "complete-predicate"],
          ["came", "simple-predicate"],
          ["The rain stopped,", "independent-clause"],
          ["and the sun came out.", "independent-clause"],
        ], { structure: "compound", purpose: "declarative" }),
        sentence("Because we practiced, we played well.", [
          ["Because", "conjunction", "A subordinating conjunction — it makes the clause dependent."],
          ["we", "pronoun"],
          ["practiced,", "verb"],
          ["we", "pronoun", "", 2],
          ["played", "verb"],
          ["well.", "adverb"],
          ["we", "simple-subject"],
          ["practiced,", "simple-predicate"],
          ["we", "simple-subject", "", 2],
          ["played well.", "complete-predicate"],
          ["played", "simple-predicate"],
          ["Because we practiced,", "dependent-clause"],
          ["Because we practiced,", "adverbial-clause", "It tells WHY they played well."],
          ["we played well.", "independent-clause"],
        ], { structure: "complex", purpose: "declarative" }),
        sentence("When the whistle blew, the crowd cheered, and the players celebrated.", [
          ["When", "conjunction"],
          ["the", "determiner"],
          ["whistle", "noun"],
          ["blew,", "verb"],
          ["the", "determiner", "", 2],
          ["crowd", "noun"],
          ["cheered,", "verb"],
          ["and", "conjunction"],
          ["the", "determiner", "", 3],
          ["players", "noun"],
          ["celebrated.", "verb"],
          ["the whistle", "complete-subject"],
          ["whistle", "simple-subject"],
          ["blew,", "simple-predicate"],
          ["the crowd", "complete-subject"],
          ["crowd", "simple-subject"],
          ["cheered,", "simple-predicate"],
          ["the players", "complete-subject"],
          ["players", "simple-subject"],
          ["celebrated.", "simple-predicate"],
          ["When the whistle blew,", "adverbial-clause", "The dependent clause — it can't stand alone."],
          ["the crowd cheered,", "independent-clause"],
          ["and the players celebrated.", "independent-clause"],
        ], { structure: "compound-complex", purpose: "declarative" }),
      ]
    );
  }

  /* ================================================================
   * Parts of Speech Close-Up — every part of speech drilled down to a
   * specific type (noun types, verb types, pronoun types, articles, …),
   * so students can practice the fine distinctions in the quiz.
   * ================================================================ */
  function buildPartsOfSpeech() {
    return make(
      "Parts of Speech Close-Up",
      "Drill-down practice: each word labeled with its specific type — common vs. proper nouns, action vs. linking vs. helping verbs, the pronoun and adjective types, articles, and more.",
      [
        sentence("The team's brave captain from London shared her courage here during the storm.", [
          ["The", "definite-article"],
          ["team's", "possessive-noun"],
          ["brave", "descriptive-adjective"],
          ["captain", "common-noun"],
          ["from", "preposition"],
          ["London", "proper-noun"],
          ["shared", "transitive-verb", "It takes a direct object — shared what? her courage."],
          ["her", "possessive-adjective"],
          ["courage", "abstract-noun"],
          ["here", "adverb-of-place"],
          ["during", "preposition"],
          ["the", "definite-article"],
          ["storm.", "concrete-noun"],
          ["The team's brave captain from London", "complete-subject"],
          ["captain", "simple-subject"],
          ["shared her courage here during the storm.", "complete-predicate"],
          ["shared", "simple-predicate"],
          ["her courage", "direct-object"],
          ["The team's brave captain from London shared her courage here during the storm.", "independent-clause"],
        ], { structure: "simple", purpose: "declarative" }),
        sentence("She is a French doctor, and she can help anyone quickly.", [
          ["She", "personal-pronoun"],
          ["is", "linking-verb"],
          ["a", "indefinite-article"],
          ["French", "proper-adjective"],
          ["doctor,", "common-noun"],
          ["and", "coordinating-conjunction"],
          ["she", "personal-pronoun"],
          ["can", "modal-verb"],
          ["help", "action-verb"],
          ["anyone", "indefinite-pronoun"],
          ["quickly.", "adverb-of-manner"],
          ["She", "simple-subject"],
          ["is a French doctor,", "complete-predicate"],
          ["is", "simple-predicate"],
          ["a French doctor,", "predicate-nominative", "A subject complement that renames “She.”"],
          ["she", "simple-subject"],
          ["can help anyone quickly.", "complete-predicate"],
          ["can help", "simple-predicate"],
          ["anyone", "direct-object"],
          ["She is a French doctor,", "independent-clause"],
          ["and she can help anyone quickly.", "independent-clause"],
        ], { structure: "compound", purpose: "declarative" }),
        sentence("They have finished, but that is not yours.", [
          ["They", "personal-pronoun"],
          ["have", "helping-verb"],
          ["finished,", "action-verb"],
          ["but", "coordinating-conjunction"],
          ["that", "demonstrative-pronoun"],
          ["is", "linking-verb", "", 2],
          ["not", "adverb-of-degree", "A negating adverb."],
          ["yours.", "possessive-pronoun"],
          ["They", "simple-subject"],
          ["have finished,", "complete-predicate", "The whole predicate — a verb phrase with no object."],
          ["that", "simple-subject"],
          ["is not yours.", "complete-predicate"],
          ["is", "simple-predicate", "", 2],
          ["yours.", "predicate-nominative", "A subject complement that renames “that.”"],
          ["They have finished,", "independent-clause"],
          ["but that is not yours.", "independent-clause"],
        ], { structure: "compound", purpose: "declarative" }),
        sentence("The icier path was the most dangerous, so we walked very carefully.", [
          ["The", "definite-article"],
          ["icier", "comparative-adjective"],
          ["path", "common-noun"],
          ["was", "linking-verb"],
          ["the", "definite-article"],
          ["most dangerous,", "superlative-adjective"],
          ["so", "coordinating-conjunction"],
          ["we", "personal-pronoun"],
          ["walked", "intransitive-verb", "No direct object — nothing receives the action."],
          ["very", "adverb-of-degree"],
          ["carefully.", "adverb-of-manner"],
          ["The icier path", "complete-subject"],
          ["path", "simple-subject"],
          ["was the most dangerous,", "complete-predicate"],
          ["was", "simple-predicate"],
          ["the most dangerous,", "predicate-adjective", "A subject complement describing the path."],
          ["we", "simple-subject"],
          ["walked very carefully.", "complete-predicate"],
          ["walked", "simple-predicate"],
          ["The icier path was the most dangerous,", "independent-clause"],
          ["so we walked very carefully.", "independent-clause"],
        ], { structure: "compound", purpose: "declarative" }),
        sentence("Which of those three books that you read is your favorite?", [
          ["Which", "interrogative-pronoun"],
          ["of", "preposition"],
          ["those", "demonstrative-adjective"],
          ["three", "quantitative-adjective"],
          ["books", "common-noun"],
          ["that", "relative-pronoun"],
          ["you", "personal-pronoun"],
          ["read", "action-verb"],
          ["is", "linking-verb"],
          ["your", "possessive-adjective"],
          ["favorite?", "descriptive-adjective"],
          ["you", "simple-subject"],
          ["read", "simple-predicate"],
          ["that you read", "relative-clause", "Describes “books.”"],
          ["Which of those three books that you read", "complete-subject"],
          ["Which", "simple-subject"],
          ["is your favorite?", "complete-predicate"],
          ["is", "simple-predicate"],
          ["your favorite?", "predicate-nominative", "A subject complement that renames “Which.”"],
          ["Which of those three books that you read is your favorite?", "independent-clause"],
        ], { structure: "complex", purpose: "interrogative" }),
        sentence("Always believe in yourself today.", [
          ["Always", "adverb-of-frequency"],
          ["believe", "action-verb", "A command — the subject “you” is understood."],
          ["in", "preposition"],
          ["yourself", "reflexive-pronoun"],
          ["today.", "adverb-of-time"],
          ["believe", "understood-subject", "The subject “(you)” is understood in a command."],
          ["Always believe in yourself today.", "complete-predicate"],
          ["believe", "simple-predicate"],
          ["in yourself", "prepositional-phrase"],
          ["Always believe in yourself today.", "independent-clause"],
        ], { structure: "simple", purpose: "imperative" }),
        sentence("Wow, neither the team nor the crowd left, because they were truly excited!", [
          ["Wow,", "interjection"],
          ["neither", "correlative-conjunction", "Half of the pair “neither … nor.”"],
          ["the", "definite-article", "", 2],
          ["team", "collective-noun"],
          ["nor", "correlative-conjunction"],
          ["the", "definite-article", "", 3],
          ["crowd", "collective-noun"],
          ["left,", "intransitive-verb"],
          ["because", "subordinating-conjunction"],
          ["they", "personal-pronoun"],
          ["were", "linking-verb"],
          ["truly", "adverb-of-degree"],
          ["excited!", "descriptive-adjective"],
          ["neither the team nor the crowd", "compound-subject", "Two subjects joined by “neither … nor.”"],
          ["team", "simple-subject"],
          ["crowd", "simple-subject"],
          ["left,", "simple-predicate"],
          ["they", "simple-subject"],
          ["were truly excited!", "complete-predicate"],
          ["were", "simple-predicate"],
          ["excited!", "predicate-adjective", "A subject complement describing “they.”"],
          ["neither the team nor the crowd left,", "independent-clause"],
          ["because they were truly excited!", "adverbial-clause", "Tells WHY they stayed."],
        ], { structure: "complex", purpose: "exclamatory" }),
      ]
    );
  }

  /* ================================================================
   * The Declaration of Independence — the opening (Thomas Jefferson, 1776)
   * The first fifteen sentences, from the Preamble through the first
   * grievances. A parts-of-speech showcase: every word is tagged and the
   * long periodic sentences deliberately stress the presentation layout.
   * Em-dashes are lightly regularized into sentence breaks; sentence-type
   * and phrase/clause layers are left off to keep the focus on word classes.
   * ================================================================ */
  function buildDeclaration() {
    return make(
      "The Declaration of Independence — Opening",
      "The first fifteen sentences of the 1776 Declaration, from the Preamble through the opening grievances. A parts-of-speech close read: every word is tagged, and Jefferson's long periodic sentences push presentation layout to its limits. (Em-dashes lightly regularized into sentence breaks; only the word layer is labeled.)",
      [
        sentence("When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.", [
          ["When", "conjunction", "Here “when” opens a long introductory clause."],
          ["in", "preposition"],
          ["the", "determiner"],
          ["Course", "noun"],
          ["of", "preposition"],
          ["human", "adjective"],
          ["events,", "noun"],
          ["it", "pronoun"],
          ["becomes", "verb"],
          ["necessary", "adjective"],
          ["for", "preposition"],
          ["one", "determiner"],
          ["people", "noun"],
          ["to dissolve", "infinitive", "“to” + the base verb — an infinitive."],
          ["the", "determiner", "", 2],
          ["political", "adjective"],
          ["bands", "noun"],
          ["which", "pronoun", "A relative pronoun standing for the bands."],
          ["have", "verb"],
          ["connected", "verb"],
          ["them", "pronoun"],
          ["with", "preposition"],
          ["another,", "pronoun"],
          ["and", "conjunction", "", 2],
          ["to assume", "infinitive"],
          ["among", "preposition"],
          ["the", "determiner", "", 5],
          ["powers", "noun"],
          ["of", "preposition", "", 2],
          ["the", "determiner", "", 6],
          ["earth,", "noun"],
          ["the", "determiner", "", 7],
          ["separate", "adjective"],
          ["and", "conjunction", "", 3],
          ["equal", "adjective"],
          ["station", "noun"],
          ["to", "preposition", "", 3],
          ["which", "pronoun", "", 2],
          ["the", "determiner", "", 8],
          ["Laws", "noun"],
          ["of", "preposition", "", 3],
          ["Nature", "noun"],
          ["and", "conjunction", "", 4],
          ["of", "preposition", "", 4],
          ["Nature's", "noun", "“Nature's” is a possessive noun."],
          ["God", "noun"],
          ["entitle", "verb"],
          ["them,", "pronoun"],
          ["a", "determiner", "", 20],
          ["decent", "adjective"],
          ["respect", "noun"],
          ["to", "preposition", "", 4],
          ["the", "determiner", "", 10],
          ["opinions", "noun"],
          ["of", "preposition", "", 5],
          ["mankind", "noun"],
          ["requires", "verb"],
          ["that", "conjunction", "“that” introduces a noun clause, so it is a conjunction here."],
          ["they", "pronoun"],
          ["should", "verb"],
          ["declare", "verb"],
          ["the", "determiner", "", 12],
          ["causes", "noun"],
          ["which", "pronoun", "", 3],
          ["impel", "verb"],
          ["them", "pronoun", "", 3],
          ["to", "preposition", "", 5],
          ["the", "determiner", "", 14],
          ["separation.", "noun"],
        ]),
        sentence("We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.", [
          ["We", "pronoun"],
          ["hold", "verb"],
          ["these", "determiner"],
          ["truths", "noun"],
          ["to be", "infinitive"],
          ["self-evident,", "adjective", "Hyphenated, so it is one token."],
          ["that", "conjunction"],
          ["all", "determiner"],
          ["men", "noun"],
          ["are", "verb"],
          ["created", "verb"],
          ["equal,", "adjective"],
          ["that", "conjunction", "", 2],
          ["they", "pronoun"],
          ["are", "verb", "", 2],
          ["endowed", "verb"],
          ["by", "preposition"],
          ["their", "determiner"],
          ["Creator", "noun"],
          ["with", "preposition"],
          ["certain", "adjective"],
          ["unalienable", "adjective", "Archaic spelling of “inalienable.”"],
          ["Rights,", "noun"],
          ["that", "conjunction", "", 3],
          ["among", "preposition"],
          ["these", "pronoun", "“these” stands alone here, so it is a pronoun.", 2],
          ["are", "verb", "", 3],
          ["Life,", "noun"],
          ["Liberty", "noun"],
          ["and", "conjunction"],
          ["the", "determiner", "", 5],
          ["pursuit", "noun"],
          ["of", "preposition"],
          ["Happiness.", "noun"],
        ]),
        sentence("That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed.", [
          ["That", "conjunction", "Carries over the “we hold that …” sense."],
          ["to secure", "infinitive"],
          ["these", "determiner"],
          ["rights,", "noun"],
          ["Governments", "noun"],
          ["are", "verb"],
          ["instituted", "verb"],
          ["among", "preposition"],
          ["Men,", "noun"],
          ["deriving", "participle", "An -ing participle describing Governments."],
          ["their", "determiner"],
          ["just", "adjective"],
          ["powers", "noun"],
          ["from", "preposition"],
          ["the", "determiner", "", 3],
          ["consent", "noun"],
          ["of", "preposition"],
          ["the", "determiner", "", 4],
          ["governed.", "noun", "“the governed” — an adjective used as a noun."],
        ]),
        sentence("That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness.", [
          ["That", "conjunction"],
          ["whenever", "conjunction"],
          ["any", "determiner"],
          ["Form", "noun"],
          ["of", "preposition"],
          ["Government", "noun"],
          ["becomes", "verb"],
          ["destructive", "adjective"],
          ["of", "preposition", "", 2],
          ["these", "determiner"],
          ["ends,", "noun"],
          ["it", "pronoun"],
          ["is", "verb"],
          ["the", "determiner", "", 2],
          ["Right", "noun"],
          ["of", "preposition", "", 3],
          ["the", "determiner", "", 3],
          ["People", "noun"],
          ["to alter", "infinitive"],
          ["or", "conjunction", "", 2],
          ["to abolish", "infinitive"],
          ["it,", "pronoun"],
          ["and", "conjunction"],
          ["to institute", "infinitive"],
          ["new", "adjective"],
          ["Government,", "noun"],
          ["laying", "participle", "Opens a participial phrase modifying Government."],
          ["its", "determiner"],
          ["foundation", "noun"],
          ["on", "preposition", "", 2],
          ["such", "determiner"],
          ["principles", "noun"],
          ["and", "conjunction", "", 2],
          ["organizing", "participle"],
          ["its", "determiner", "", 2],
          ["powers", "noun"],
          ["in", "preposition", "", 5],
          ["such", "determiner", "", 2],
          ["form,", "noun"],
          ["as", "conjunction", "“as” introduces a comparison clause."],
          ["to", "preposition", "", 4],
          ["them", "pronoun"],
          ["shall", "verb"],
          ["seem", "verb"],
          ["most", "adverb"],
          ["likely", "adjective"],
          ["to effect", "infinitive"],
          ["their", "determiner"],
          ["Safety", "noun"],
          ["and", "conjunction", "", 3],
          ["Happiness.", "noun"],
        ]),
        sentence("Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed.", [
          ["Prudence,", "noun"],
          ["indeed,", "adverb"],
          ["will", "verb"],
          ["dictate", "verb"],
          ["that", "conjunction"],
          ["Governments", "noun"],
          ["long", "adverb"],
          ["established", "participle", "A past participle modifying Governments."],
          ["should", "verb"],
          ["not", "adverb"],
          ["be", "verb"],
          ["changed", "verb"],
          ["for", "preposition"],
          ["light", "adjective"],
          ["and", "conjunction"],
          ["transient", "adjective"],
          ["causes;", "noun"],
          ["and", "conjunction", "", 2],
          ["accordingly", "adverb"],
          ["all", "determiner"],
          ["experience", "noun"],
          ["hath", "verb", "Archaic form of “has.”"],
          ["shewn,", "verb", "Archaic spelling of “shown.”"],
          ["that", "conjunction", "", 2],
          ["mankind", "noun"],
          ["are", "verb"],
          ["more", "adverb"],
          ["disposed", "adjective", "Predicate adjective — “inclined.”"],
          ["to suffer,", "infinitive"],
          ["while", "conjunction"],
          ["evils", "noun"],
          ["are", "verb", "", 2],
          ["sufferable,", "adjective"],
          ["than", "conjunction"],
          ["to right", "infinitive", "Here “right” is a verb — “to set right.”"],
          ["themselves", "pronoun", "A reflexive pronoun."],
          ["by", "preposition"],
          ["abolishing", "gerund", "An -ing verb form acting as a noun."],
          ["the", "determiner", "", 2],
          ["forms", "noun"],
          ["to", "preposition", "", 3],
          ["which", "pronoun"],
          ["they", "pronoun"],
          ["are", "verb", "", 3],
          ["accustomed.", "adjective", "Predicate adjective after “are.”"],
        ]),
        sentence("But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.", [
          ["But", "conjunction"],
          ["when", "conjunction"],
          ["a", "determiner"],
          ["long", "adjective"],
          ["train", "noun"],
          ["of", "preposition"],
          ["abuses", "noun"],
          ["and", "conjunction"],
          ["usurpations,", "noun"],
          ["pursuing", "participle", "Opens a participial phrase."],
          ["invariably", "adverb"],
          ["the", "determiner"],
          ["same", "adjective"],
          ["Object", "noun"],
          ["evinces", "verb"],
          ["a", "determiner", "", 9],
          ["design", "noun"],
          ["to reduce", "infinitive"],
          ["them", "pronoun"],
          ["under", "preposition"],
          ["absolute", "adjective"],
          ["Despotism,", "noun"],
          ["it", "pronoun"],
          ["is", "verb", "", 2],
          ["their", "determiner"],
          ["right,", "noun"],
          ["it", "pronoun", "", 2],
          ["is", "verb", "", 3],
          ["their", "determiner", "", 2],
          ["duty,", "noun"],
          ["to throw", "infinitive"],
          ["off", "adverb", "A particle completing the phrasal verb “throw off.”"],
          ["such", "determiner"],
          ["Government,", "noun"],
          ["and", "conjunction", "", 2],
          ["to provide", "infinitive"],
          ["new", "adjective"],
          ["Guards", "noun"],
          ["for", "preposition"],
          ["their", "determiner", "", 3],
          ["future", "adjective"],
          ["security.", "noun"],
        ]),
        sentence("Such has been the patient sufferance of these Colonies; and such is now the necessity which constrains them to alter their former Systems of Government.", [
          ["Such", "pronoun", "“Such” stands in for the whole prior idea, so it is a pronoun."],
          ["has", "verb"],
          ["been", "verb"],
          ["the", "determiner"],
          ["patient", "adjective"],
          ["sufferance", "noun"],
          ["of", "preposition"],
          ["these", "determiner"],
          ["Colonies;", "noun"],
          ["and", "conjunction"],
          ["such", "pronoun"],
          ["is", "verb"],
          ["now", "adverb"],
          ["the", "determiner", "", 3],
          ["necessity", "noun"],
          ["which", "pronoun"],
          ["constrains", "verb"],
          ["them", "pronoun"],
          ["to alter", "infinitive"],
          ["their", "determiner"],
          ["former", "adjective"],
          ["Systems", "noun"],
          ["of", "preposition", "", 2],
          ["Government.", "noun"],
        ]),
        sentence("The history of the present King of Great Britain is a history of repeated injuries and usurpations, all having in direct object the establishment of an absolute Tyranny over these States.", [
          ["The", "determiner"],
          ["history", "noun"],
          ["of", "preposition"],
          ["the", "determiner"],
          ["present", "adjective"],
          ["King", "noun"],
          ["of", "preposition", "", 2],
          ["Great", "adjective"],
          ["Britain", "noun"],
          ["is", "verb", "", 2],
          ["a", "determiner", "", 3],
          ["history", "noun", "", 2],
          ["of", "preposition", "", 3],
          ["repeated", "adjective"],
          ["injuries", "noun"],
          ["and", "conjunction"],
          ["usurpations,", "noun"],
          ["all", "pronoun", "“all” stands alone as the subject of the phrase."],
          ["having", "participle", "An -ing participle."],
          ["in", "preposition", "", 5],
          ["direct", "adjective"],
          ["object", "noun"],
          ["the", "determiner", "", 2],
          ["establishment", "noun"],
          ["of", "preposition", "", 4],
          ["an", "determiner", "", 2],
          ["absolute", "adjective"],
          ["Tyranny", "noun"],
          ["over", "preposition"],
          ["these", "determiner"],
          ["States.", "noun"],
        ]),
        sentence("To prove this, let Facts be submitted to a candid world.", [
          ["To prove", "infinitive", "An infinitive phrase opens the sentence."],
          ["this,", "pronoun", "A demonstrative pronoun — the object of “prove.”"],
          ["let", "verb"],
          ["Facts", "noun"],
          ["be", "verb"],
          ["submitted", "verb"],
          ["to", "preposition"],
          ["a", "determiner", "", 2],
          ["candid", "adjective"],
          ["world.", "noun"],
        ]),
        sentence("He has refused his Assent to Laws, the most wholesome and necessary for the public good.", [
          ["He", "pronoun"],
          ["has", "verb"],
          ["refused", "verb"],
          ["his", "determiner"],
          ["Assent", "noun"],
          ["to", "preposition"],
          ["Laws,", "noun"],
          ["the", "determiner"],
          ["most", "adverb", "“most” forms the superlative — an adverb of degree."],
          ["wholesome", "adjective"],
          ["and", "conjunction"],
          ["necessary", "adjective"],
          ["for", "preposition"],
          ["the", "determiner", "", 2],
          ["public", "adjective"],
          ["good.", "noun"],
        ]),
        sentence("He has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.", [
          ["He", "pronoun"],
          ["has", "verb"],
          ["forbidden", "verb"],
          ["his", "determiner"],
          ["Governors", "noun"],
          ["to pass", "infinitive"],
          ["Laws", "noun"],
          ["of", "preposition"],
          ["immediate", "adjective"],
          ["and", "conjunction"],
          ["pressing", "adjective"],
          ["importance,", "noun"],
          ["unless", "conjunction"],
          ["suspended", "participle", "A past participle — “unless [they are] suspended.”"],
          ["in", "preposition", "", 2],
          ["their", "determiner"],
          ["operation", "noun"],
          ["till", "conjunction", "“till” introduces a clause, so it acts as a conjunction."],
          ["his", "determiner", "", 2],
          ["Assent", "noun"],
          ["should", "verb"],
          ["be", "verb"],
          ["obtained;", "verb"],
          ["and", "conjunction", "", 2],
          ["when", "conjunction"],
          ["so", "adverb"],
          ["suspended,", "participle"],
          ["he", "pronoun", "", 3],
          ["has", "verb", "", 2],
          ["utterly", "adverb"],
          ["neglected", "verb"],
          ["to attend", "infinitive"],
          ["to", "preposition", "", 3],
          ["them.", "pronoun"],
        ]),
        sentence("He has refused to pass other Laws for the accommodation of large districts of people, unless those people would relinquish the right of Representation in the Legislature, a right inestimable to them and formidable to tyrants only.", [
          ["He", "pronoun"],
          ["has", "verb"],
          ["refused", "verb"],
          ["to pass", "infinitive"],
          ["other", "adjective"],
          ["Laws", "noun"],
          ["for", "preposition"],
          ["the", "determiner", "", 2],
          ["accommodation", "noun"],
          ["of", "preposition"],
          ["large", "adjective"],
          ["districts", "noun"],
          ["of", "preposition", "", 2],
          ["people,", "noun"],
          ["unless", "conjunction"],
          ["those", "determiner"],
          ["people", "noun", "", 2],
          ["would", "verb"],
          ["relinquish", "verb"],
          ["the", "determiner", "", 3],
          ["right", "noun"],
          ["of", "preposition", "", 3],
          ["Representation", "noun"],
          ["in", "preposition", "", 2],
          ["the", "determiner", "", 4],
          ["Legislature,", "noun"],
          ["a", "determiner", "", 9],
          ["right", "noun", "", 2],
          ["inestimable", "adjective"],
          ["to", "preposition", "", 2],
          ["them", "pronoun"],
          ["and", "conjunction"],
          ["formidable", "adjective"],
          ["to", "preposition", "", 3],
          ["tyrants", "noun"],
          ["only.", "adverb", "“only” limits the phrase — an adverb."],
        ]),
        sentence("He has called together legislative bodies at places unusual, uncomfortable, and distant from the depository of their public Records, for the sole purpose of fatiguing them into compliance with his measures.", [
          ["He", "pronoun"],
          ["has", "verb"],
          ["called", "verb"],
          ["together", "adverb", "A particle completing “called together.”"],
          ["legislative", "adjective"],
          ["bodies", "noun"],
          ["at", "preposition", "", 2],
          ["places", "noun"],
          ["unusual,", "adjective"],
          ["uncomfortable,", "adjective"],
          ["and", "conjunction"],
          ["distant", "adjective"],
          ["from", "preposition"],
          ["the", "determiner", "", 2],
          ["depository", "noun"],
          ["of", "preposition"],
          ["their", "determiner"],
          ["public", "adjective"],
          ["Records,", "noun"],
          ["for", "preposition", "", 2],
          ["the", "determiner", "", 4],
          ["sole", "adjective"],
          ["purpose", "noun"],
          ["of", "preposition", "", 2],
          ["fatiguing", "gerund", "An -ing verb form acting as a noun."],
          ["them", "pronoun"],
          ["into", "preposition"],
          ["compliance", "noun"],
          ["with", "preposition"],
          ["his", "determiner"],
          ["measures.", "noun"],
        ]),
        sentence("He has dissolved Representative Houses repeatedly, for opposing with manly firmness his invasions on the rights of the people.", [
          ["He", "pronoun"],
          ["has", "verb"],
          ["dissolved", "verb"],
          ["Representative", "adjective"],
          ["Houses", "noun"],
          ["repeatedly,", "adverb"],
          ["for", "preposition"],
          ["opposing", "gerund", "An -ing verb form acting as a noun."],
          ["with", "preposition"],
          ["manly", "adjective"],
          ["firmness", "noun"],
          ["his", "determiner"],
          ["invasions", "noun"],
          ["on", "preposition", "", 2],
          ["the", "determiner"],
          ["rights", "noun"],
          ["of", "preposition"],
          ["the", "determiner", "", 2],
          ["people.", "noun"],
        ]),
        sentence("He has refused for a long time, after such dissolutions, to cause others to be elected; whereby the Legislative powers, incapable of Annihilation, have returned to the People at large for their exercise; the State remaining in the mean time exposed to all the dangers of invasion from without, and convulsions within.", [
          ["He", "pronoun"],
          ["has", "verb"],
          ["refused", "verb"],
          ["for", "preposition"],
          ["a", "determiner", "", 2],
          ["long", "adjective"],
          ["time,", "noun"],
          ["after", "preposition"],
          ["such", "determiner"],
          ["dissolutions,", "noun"],
          ["to cause", "infinitive"],
          ["others", "pronoun"],
          ["to be", "infinitive"],
          ["elected;", "participle", "A past participle — passive infinitive “to be elected.”"],
          ["whereby", "conjunction", "“whereby” links this result to the cause."],
          ["the", "determiner", "", 2],
          ["Legislative", "adjective"],
          ["powers,", "noun"],
          ["incapable", "adjective"],
          ["of", "preposition"],
          ["Annihilation,", "noun"],
          ["have", "verb"],
          ["returned", "verb"],
          ["to", "preposition", "", 3],
          ["the", "determiner", "", 3],
          ["People", "noun"],
          ["at", "preposition", "", 3],
          ["large", "adjective"],
          ["for", "preposition", "", 2],
          ["their", "determiner"],
          ["exercise;", "noun"],
          ["the", "determiner", "", 5],
          ["State", "noun"],
          ["remaining", "participle", "Opens an absolute phrase — “the State remaining …”"],
          ["in", "preposition", "", 4],
          ["the", "determiner", "", 6],
          ["mean", "adjective"],
          ["time", "noun", "", 2],
          ["exposed", "participle", "A past participle in the absolute phrase."],
          ["to", "preposition", "", 4],
          ["all", "determiner"],
          ["the", "determiner", "", 7],
          ["dangers", "noun"],
          ["of", "preposition", "", 2],
          ["invasion", "noun"],
          ["from", "preposition"],
          ["without,", "adverb", "“from without” — from the outside."],
          ["and", "conjunction"],
          ["convulsions", "noun"],
          ["within.", "adverb", "“within” — inside."],
        ]),
      ]
    );
  }

  /* ================================================================
   * The Declaration of Independence — full analysis (first 3 sentences)
   * A companion to buildDeclaration above: the SAME opening sentences,
   * but tagged at every layer the app supports — parts of speech,
   * sentence parts, phrases, clauses, and the sentence-type badges —
   * rather than the word layer alone. These three periodic sentences
   * are syntactically dense (sentence 1 nests two relative clauses and
   * a noun clause inside a long introductory adverbial clause), so the
   * clause and part spans reflect defensible choices, not the only ones.
   * Kept short on purpose: three sentences is already a heavy display.
   * ================================================================ */
  function buildDeclarationFull() {
    return make(
      "The Declaration of Independence — Full Analysis",
      "The first three sentences of the 1776 Declaration, tagged at every layer the app supports: parts of speech, sentence parts, phrases, clauses, and the structure/purpose badges. A companion to the parts-of-speech-only “Opening” lesson — same text, the full loadout. Jefferson's long periodic sentences make the clause and phrase nesting a genuine stress test of the presentation view.",
      [
        sentence("When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.", [
          /* -- parts of speech -- */
          ["When", "conjunction", "Here “when” opens a long introductory clause."],
          ["in", "preposition"],
          ["the", "determiner"],
          ["Course", "noun"],
          ["of", "preposition"],
          ["human", "adjective"],
          ["events,", "noun"],
          ["it", "pronoun"],
          ["becomes", "verb"],
          ["necessary", "adjective"],
          ["for", "preposition"],
          ["one", "determiner"],
          ["people", "noun"],
          ["to dissolve", "infinitive", "“to” + the base verb — an infinitive."],
          ["the", "determiner", "", 2],
          ["political", "adjective"],
          ["bands", "noun"],
          ["which", "pronoun", "A relative pronoun standing for the bands."],
          ["have", "verb"],
          ["connected", "verb"],
          ["them", "pronoun"],
          ["with", "preposition"],
          ["another,", "pronoun"],
          ["and", "conjunction", "", 2],
          ["to assume", "infinitive"],
          ["among", "preposition"],
          ["the", "determiner", "", 5],
          ["powers", "noun"],
          ["of", "preposition", "", 2],
          ["the", "determiner", "", 6],
          ["earth,", "noun"],
          ["the", "determiner", "", 7],
          ["separate", "adjective"],
          ["and", "conjunction", "", 3],
          ["equal", "adjective"],
          ["station", "noun"],
          ["to", "preposition", "", 3],
          ["which", "pronoun", "", 2],
          ["the", "determiner", "", 8],
          ["Laws", "noun"],
          ["of", "preposition", "", 3],
          ["Nature", "noun"],
          ["and", "conjunction", "", 4],
          ["of", "preposition", "", 4],
          ["Nature's", "noun", "“Nature's” is a possessive noun."],
          ["God", "noun"],
          ["entitle", "verb"],
          ["them,", "pronoun"],
          ["a", "determiner", "", 20],
          ["decent", "adjective"],
          ["respect", "noun"],
          ["to", "preposition", "", 4],
          ["the", "determiner", "", 10],
          ["opinions", "noun"],
          ["of", "preposition", "", 5],
          ["mankind", "noun"],
          ["requires", "verb"],
          ["that", "conjunction", "“that” introduces a noun clause, so it is a conjunction here."],
          ["they", "pronoun"],
          ["should", "verb"],
          ["declare", "verb"],
          ["the", "determiner", "", 12],
          ["causes", "noun"],
          ["which", "pronoun", "", 3],
          ["impel", "verb"],
          ["them", "pronoun", "", 3],
          ["to", "preposition", "", 5],
          ["the", "determiner", "", 14],
          ["separation.", "noun"],

          /* -- sentence parts -- */
          ["it", "simple-subject", "The anticipatory “it” — the grammatical subject of the introductory clause."],
          ["becomes", "simple-predicate"],
          ["necessary", "predicate-adjective", "Follows the linking verb “becomes” and describes “it.”"],
          ["which", "simple-subject", "The relative pronoun is the subject of its own clause.", 1],
          ["have connected", "simple-predicate"],
          ["the Laws of Nature and of Nature's God", "complete-subject", "The subject of the “to which … entitle” clause."],
          ["Laws", "simple-subject"],
          ["entitle", "simple-predicate"],
          ["a decent respect to the opinions of mankind", "complete-subject", "The full subject of the main clause."],
          ["respect", "simple-subject"],
          ["requires that they should declare the causes which impel them to the separation.", "complete-predicate"],
          ["requires", "simple-predicate"],
          ["they", "simple-subject"],
          ["should declare", "simple-predicate"],
          ["which", "simple-subject", "", 3],
          ["impel", "simple-predicate"],
          ["the political bands", "direct-object", "What it becomes necessary “to dissolve.”"],
          ["the causes", "direct-object", "The object of “declare.”"],
          ["mankind", "object-of-preposition"],
          ["the separation.", "object-of-preposition"],

          /* -- phrases -- */
          ["in the Course of human events,", "prepositional-phrase", "Tells when it becomes necessary."],
          ["of human events,", "prepositional-phrase"],
          ["to dissolve the political bands", "infinitive-phrase", "The first of two parallel infinitive phrases."],
          ["the political bands", "noun-phrase"],
          ["with another,", "prepositional-phrase"],
          ["to assume among the powers of the earth, the separate and equal station", "infinitive-phrase", "The second parallel infinitive — its object “the station” trails the phrase."],
          ["among the powers of the earth,", "prepositional-phrase"],
          ["of the earth,", "prepositional-phrase"],
          ["the separate and equal station", "noun-phrase"],
          ["to the opinions of mankind", "prepositional-phrase"],
          ["of mankind", "prepositional-phrase"],
          ["to the separation.", "prepositional-phrase"],

          /* -- clauses -- */
          ["When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them,", "adverbial-clause", "The long introductory clause telling when the main statement holds."],
          ["which have connected them with another,", "relative-clause", "Describes the political bands."],
          ["to which the Laws of Nature and of Nature's God entitle them,", "relative-clause", "Describes the station; the preposition “to” is fronted with “which.”"],
          ["a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.", "independent-clause", "The main clause — everything before it is introductory."],
          ["that they should declare the causes which impel them to the separation.", "noun-clause", "The direct object of “requires” — it names what respect requires."],
          ["which impel them to the separation.", "relative-clause", "Describes the causes."],
        ], { structure: "complex", purpose: "declarative" },
          "One independent clause carrying a long introductory adverbial clause and, inside the main clause, a noun clause (the object of “requires”) with its own relative clause — so the whole sentence is complex, not compound."),

        sentence("We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.", [
          /* -- parts of speech -- */
          ["We", "pronoun"],
          ["hold", "verb"],
          ["these", "determiner"],
          ["truths", "noun"],
          ["to be", "infinitive"],
          ["self-evident,", "adjective", "Hyphenated, so it is one token."],
          ["that", "conjunction"],
          ["all", "determiner"],
          ["men", "noun"],
          ["are", "verb"],
          ["created", "verb"],
          ["equal,", "adjective"],
          ["that", "conjunction", "", 2],
          ["they", "pronoun"],
          ["are", "verb", "", 2],
          ["endowed", "verb"],
          ["by", "preposition"],
          ["their", "determiner"],
          ["Creator", "noun"],
          ["with", "preposition"],
          ["certain", "adjective"],
          ["unalienable", "adjective", "Archaic spelling of “inalienable.”"],
          ["Rights,", "noun"],
          ["that", "conjunction", "", 3],
          ["among", "preposition"],
          ["these", "pronoun", "“these” stands alone here, so it is a pronoun.", 2],
          ["are", "verb", "", 3],
          ["Life,", "noun"],
          ["Liberty", "noun"],
          ["and", "conjunction"],
          ["the", "determiner", "", 5],
          ["pursuit", "noun"],
          ["of", "preposition"],
          ["Happiness.", "noun"],

          /* -- sentence parts -- */
          ["We", "simple-subject"],
          ["hold these truths to be self-evident,", "complete-predicate"],
          ["hold", "simple-predicate"],
          ["these truths", "direct-object", "What “we hold.”"],
          ["self-evident,", "object-complement", "Describes “these truths” — what we hold them to be."],
          ["men", "simple-subject"],
          ["are created", "simple-predicate"],
          ["equal,", "predicate-adjective"],
          ["they", "simple-subject"],
          ["are endowed", "simple-predicate"],
          ["their Creator", "object-of-preposition"],
          ["certain unalienable Rights,", "object-of-preposition"],
          ["Life, Liberty and the pursuit of Happiness.", "compound-subject", "Three subjects sharing the verb “are”; the clause is inverted (“… are Life, Liberty …”)."],
          ["are", "simple-predicate", "", 3],

          /* -- phrases -- */
          ["these truths", "noun-phrase"],
          ["to be self-evident,", "infinitive-phrase", "Acts as the complement of “these truths.”"],
          ["are created", "verb-phrase", "Passive voice — helping verb “are” plus the participle “created.”"],
          ["are endowed", "verb-phrase"],
          ["by their Creator", "prepositional-phrase"],
          ["with certain unalienable Rights,", "prepositional-phrase"],
          ["certain unalienable Rights,", "noun-phrase"],
          ["among these", "prepositional-phrase"],
          ["the pursuit of Happiness.", "noun-phrase"],
          ["of Happiness.", "prepositional-phrase"],

          /* -- clauses -- */
          ["We hold these truths to be self-evident,", "independent-clause", "The main clause; the three “that …” clauses that follow all stand in apposition to “these truths.”"],
          ["that all men are created equal,", "noun-clause", "First of three noun clauses naming the truths held."],
          ["that they are endowed by their Creator with certain unalienable Rights,", "noun-clause"],
          ["that among these are Life, Liberty and the pursuit of Happiness.", "noun-clause"],
        ], { structure: "complex", purpose: "declarative" },
          "The main clause “We hold these truths …” takes three parallel noun clauses (each opening with “that”) that unpack the truths — an independent clause plus dependent clauses, so it is complex."),

        sentence("That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed.", [
          /* -- parts of speech -- */
          ["That", "conjunction", "Carries over the “we hold that …” sense."],
          ["to secure", "infinitive"],
          ["these", "determiner"],
          ["rights,", "noun"],
          ["Governments", "noun"],
          ["are", "verb"],
          ["instituted", "verb"],
          ["among", "preposition"],
          ["Men,", "noun"],
          ["deriving", "participle", "An -ing participle describing Governments."],
          ["their", "determiner"],
          ["just", "adjective"],
          ["powers", "noun"],
          ["from", "preposition"],
          ["the", "determiner", "", 3],
          ["consent", "noun"],
          ["of", "preposition"],
          ["the", "determiner", "", 4],
          ["governed.", "noun", "“the governed” — an adjective used as a noun."],

          /* -- sentence parts -- */
          ["Governments", "simple-subject"],
          ["are instituted among Men, deriving their just powers from the consent of the governed.", "complete-predicate"],
          ["are instituted", "simple-predicate"],
          ["these rights,", "direct-object", "What the Governments are instituted “to secure.”"],
          ["their just powers", "direct-object", "The object of the participle “deriving.”"],
          ["Men,", "object-of-preposition"],
          ["the consent of the governed.", "object-of-preposition"],
          ["the governed.", "object-of-preposition"],

          /* -- phrases -- */
          ["to secure these rights,", "infinitive-phrase", "Tells why Governments are instituted."],
          ["these rights,", "noun-phrase"],
          ["are instituted", "verb-phrase", "Passive voice — “are” plus the participle “instituted.”"],
          ["among Men,", "prepositional-phrase"],
          ["deriving their just powers from the consent of the governed.", "participial-phrase", "Describes Governments — how they hold their power."],
          ["their just powers", "noun-phrase"],
          ["from the consent of the governed.", "prepositional-phrase"],
          ["the consent of the governed.", "noun-phrase"],
          ["of the governed.", "prepositional-phrase"],

          /* -- clauses -- */
          ["That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed.", "independent-clause", "A single independent clause; the infinitive and participial phrases are not clauses, so the sentence is simple."],
        ], { structure: "simple", purpose: "declarative" },
          "One independent clause — “Governments are instituted” — framed by an infinitive phrase (“to secure these rights”) and a participial phrase (“deriving …”); neither is a clause, so the structure is simple."),
      ]
    );
  }

  /* ---------------------------------------------------------------- *
   * Registry. The fox demo (defined in store.js) leads the list.
   * ---------------------------------------------------------------- */
  wjt.EXAMPLES = [
    {
      id: "fox",
      title: "The Fox and the River",
      subtitle: "Starter demo · every level labeled",
      build: wjt.buildSampleLesson,
    },
    {
      id: "parts-of-speech-close-up",
      title: "Parts of Speech Close-Up",
      subtitle: "Word types · noun, verb & pronoun types, articles",
      build: buildPartsOfSpeech,
    },
    {
      id: "declaration-of-independence",
      title: "The Declaration of Independence — Opening",
      subtitle: "Jefferson · 15 sentences, every word tagged",
      build: buildDeclaration,
    },
    {
      id: "declaration-of-independence-full",
      title: "The Declaration of Independence — Full Analysis",
      subtitle: "Jefferson · first 3 sentences, every layer tagged",
      build: buildDeclarationFull,
    },
    {
      id: "kinds-of-sentences",
      title: "Kinds of Sentences",
      subtitle: "Types · four purposes & four structures",
      build: buildKinds,
    },
    {
      id: "romeo-juliet-prologue",
      title: "Romeo and Juliet — Prologue",
      subtitle: "Shakespeare · the Chorus's sonnet",
      build: buildRomeoJuliet,
    },
    {
      id: "great-gatsby-closing",
      title: "The Great Gatsby — Closing Lines",
      subtitle: "Fitzgerald · phrases & compound sentences",
      build: buildGatsby,
    },
    {
      id: "frankenstein-creation",
      title: "Frankenstein — The Creation",
      subtitle: "Shelley · complex & cleft sentences",
      build: buildFrankenstein,
    },
    {
      id: "dracula-count-appears",
      title: "Dracula — The Count Appears",
      subtitle: "Stoker · participles & clauses",
      build: buildDracula,
    },
  ];
})();
