/* Regenerate every document that is derived from the taxonomy in js/labels.js.
 *
 *   node tools/gen-docs.js          write the files
 *   node tools/gen-docs.js --check  exit 1 if anything would change (used by CI)
 *
 * Writes:
 *   docs/coverage-labels.json          every span label + sentence type + counts
 *   docs/coverage-labels.csv           the same span labels as a flat table
 *   docs/product/grammar-reference.md  the teacher-facing label reference
 *
 * These three are generated on purpose: hand-maintained copies of an 87-label
 * taxonomy go stale within one change. Edit js/labels.js and rerun this. */
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.join(__dirname, "..");
const check = process.argv.includes("--check");

const ctx = {};
ctx.window = ctx;
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root, "js/labels.js"), "utf8"), ctx, { filename: "labels.js" });
const wjt = ctx.wjt;

/* ---------- shared views over the taxonomy ---------- */
const ids = Object.keys(wjt.LABELS);
const rows = ids.map((id) => {
  const l = wjt.LABELS[id];
  return { id, layer: l.layer, parent: l.parent || "", name: l.name, abbr: l.abbr, color: l.color, tier: l.tier };
});
const sentenceTypes = [];
for (const axis of wjt.SENTENCE_TYPE_ORDER) {
  const cat = wjt.SENTENCE_TYPES[axis];
  for (const opt of Object.keys(cat.options)) {
    const o = cat.options[opt];
    sentenceTypes.push({ axis, id: opt, name: o.name, abbr: o.abbr, color: o.color });
  }
}
const childrenOf = (id) => ids.filter((k) => wjt.LABELS[k].parent === id);
const basesIn = (layer) => ids.filter((k) => wjt.LABELS[k].layer === layer && !wjt.LABELS[k].parent);

/* ---------- docs/coverage-labels.json ---------- */
const byTier = {};
for (const r of rows) byTier[r.tier] = (byTier[r.tier] || 0) + 1;
const json = JSON.stringify(
  { spanLabels: rows, sentenceTypes, counts: { spanLabels: rows.length, sentenceTypes: sentenceTypes.length, byTier } },
  null, 2
);

/* ---------- docs/coverage-labels.csv ---------- */
let csv = "layer,id,parent,name,abbr,color,tier\n";
for (const r of rows) {
  csv += [r.layer, r.id, r.parent, JSON.stringify(r.name), r.abbr, r.color, r.tier].join(",") + "\n";
}

/* ---------- docs/product/grammar-reference.md ---------- */
// labels.js writes examples with <b> for the browser popover; markdown wants **.
const md = (s) => String(s || "").replace(/<\/?b>/g, "**").replace(/\|/g, "\\|");
const flag = (l) => (l.tier === "advanced" ? " ⚑" : "");

let ref = `<!-- GENERATED by tools/gen-docs.js from js/labels.js — do not edit by hand. -->
# Sentence Forge — label reference

Every label the app supports, in the same words it uses on screen. Use this to
decide **which label you mean**; the \`id\` in each row is what you write when you
build a lesson file by hand or with a custom GPT.

- **Layers.** Four teaching levels, smallest unit first. A lesson's \`layers\`
  array holds the layer ids below.
- **Drill-down.** Every layer has base labels that can be applied on their own or
  opened to a more specific subtype. A subtype behaves exactly like its base —
  same color family, same quiz treatment.
- **⚑ Advanced.** Four labels sit outside the classroom-core set and are hidden
  by a lesson's **Essential only** toggle. Everything else is Essential.

| Layer | id | Unit | Labels |
|---|---|---|---|
`;
for (const layer of Object.keys(wjt.LAYERS)) {
  const L = wjt.LAYERS[layer];
  const n = ids.filter((k) => wjt.LABELS[k].layer === layer).length;
  const b = basesIn(layer).length;
  ref += `| ${L.name} | \`${layer}\` | ${L.unit} | ${b} base + ${n - b} subtypes = **${n}** |\n`;
}
ref += `\n**Totals:** ${rows.length} span labels (${byTier.essential || 0} Essential, ${byTier.advanced || 0} Advanced) plus ${sentenceTypes.length} sentence-type badges.\n\n---\n`;

for (const layer of Object.keys(wjt.LAYERS)) {
  const L = wjt.LAYERS[layer];
  ref += `\n## ${L.name} — layer id \`${layer}\`\n\n${L.hint}\n`;
  for (const id of basesIn(layer)) {
    const x = wjt.LABELS[id];
    ref += `\n### ${x.name} — \`${id}\`${flag(x)}\n\n${md(x.desc)}\n`;
    if (x.example) ref += `\n> ${md(x.example)}\n`;
    const kids = childrenOf(id);
    if (kids.length) {
      ref += `\n| Subtype | id | What it is | Example |\n|---|---|---|---|\n`;
      for (const k of kids) {
        const y = wjt.LABELS[k];
        ref += `| ${y.name}${flag(y)} | \`${k}\` | ${md(y.desc)} | ${md(y.example)} |\n`;
      }
    }
  }
}

ref += `\n---\n\n## Sentence types\n\nSet per sentence, on two independent axes — these are whole-sentence badges, not\nspan labels. In a lesson file they go in a sentence's optional \`types\` object.\n`;
for (const axis of wjt.SENTENCE_TYPE_ORDER) {
  const cat = wjt.SENTENCE_TYPES[axis];
  ref += `\n### ${cat.name} — \`types.${axis}\`\n\n${md(cat.hint || "")}\n\n| Value | Name | What it is | Example |\n|---|---|---|---|\n`;
  for (const opt of Object.keys(cat.options)) {
    const o = cat.options[opt];
    ref += `| \`${opt}\` | ${o.name} | ${md(o.desc)} | ${md(o.example)} |\n`;
  }
}
ref += `\n---\n\nMachine-readable versions of this table: [\`coverage-labels.json\`](../coverage-labels.json)\nand [\`coverage-labels.csv\`](../coverage-labels.csv). The gap-analysis view of the\nsame taxonomy is [\`coverage-brief.md\`](../coverage-brief.md).\n`;

/* ---------- write or check ---------- */
const outputs = [
  ["docs/coverage-labels.json", json],
  ["docs/coverage-labels.csv", csv],
  ["docs/product/grammar-reference.md", ref],
];

let stale = 0;
for (const [rel, content] of outputs) {
  const file = path.join(root, rel);
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (current === content) {
    console.log("  ok    " + rel);
  } else if (check) {
    console.log(" STALE  " + rel);
    stale++;
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(" wrote  " + rel);
  }
}

if (stale) {
  console.log("\n" + stale + " generated file(s) out of date — run: node tools/gen-docs.js");
  process.exit(1);
}
console.log("\n" + rows.length + " span labels, " + sentenceTypes.length + " sentence types.");
